---

- name: Check if Java is installed
  command: java -version
  register: java_version_check
  failed_when: false
  changed_when: false

- name: Install Java 1.8.0 OpenJDK (CentOS/RHEL 7)
  dnf:
    name:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
    state: present
  become: yes

- name: Check if /rnd directory exists
  stat:
    path: /rnd
  register: rnd_directory

- name: Create /rnd directory if not exists
  file:
    path: /rnd
    state: directory
    mode: '0755'
  become: yes
  when: not rnd_directory.stat.exists

- name: Ensure /rnd directory has correct permissions
  file:
    path: /rnd
    mode: '0755'
  become: yes
  when: rnd_directory.stat.exists and rnd_directory.stat.mode != '0755'